version: '3.8'

services:
  remotion-dev:
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - .:/app
      - /app/node_modules
      - ./renders:/app/renders
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - PROXY_URL=http://rotating-tor-proxy:3128
    stdin_open: true
    tty: true

  rotating-tor-proxy:
      image: zhaowde/rotating-tor-http-proxy
      container_name: rotating-tor-proxy
      ports:
        - "3128:3128"
        - "4444:4444"
      environment:
        - TOR_INSTANCES=5
      restart: always
      logging:
        driver: "none"